# version: '3.9'

services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - "8001:5432"  # 👈 expose port to host machine
    volumes:
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 134217728  # 128MB in bytes
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mydb

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080